import 'package:isar/isar.dart';

part 'farm_data.g.dart'; // This file will be generated by Isar

@collection
class FarmData {
  Id? id; // Isar will auto-increment this ID

  String? name;
  String? cropTypeKey;
  double? farmLength;
  double? farmBreadth;
  int? rows;
  int? plantsPerRow;

  FarmData({
    this.id,
    this.name,
    this.cropTypeKey,
    this.farmLength,
    this.farmBreadth,
    this.rows,
    this.plantsPerRow,
  });

  // Factory constructor to create a FarmData instance from a map
  // This is useful for migrating from your old SharedPreferences data
  factory FarmData.fromMap(Map<String, dynamic> map) {
    return FarmData(
      // The ID is not in the map, Isar will assign it
      name: map['name'] as String?,
      cropTypeKey: map['cropTypeKey'] as String?,
      farmLength: (map['farmLength'] as num?)?.toDouble(),
      farmBreadth: (map['farmBreadth'] as num?)?.toDouble(),
      rows: map['rows'] as int?,
      plantsPerRow: map['plantsPerRow'] as int?,
    );
  }
}
