// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAs_TPPh9kPwktZ6lngv7PxNoH572_iMf4',
    appId: '1:852916987468:web:41be5b31139ae15429b6e9',
    messagingSenderId: '852916987468',
    projectId: 'agrisense-pot511-1e6f7',
    authDomain: 'agrisense-pot511-1e6f7.firebaseapp.com',
    storageBucket: 'agrisense-pot511-1e6f7.firebasestorage.app',
    measurementId: 'G-717FHW8BHQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDIBQnBVG7Ax8dm_YPm5TGQC2haWjMaloQ',
    appId: '1:852916987468:android:2a526f090414adbb29b6e9',
    messagingSenderId: '852916987468',
    projectId: 'agrisense-pot511-1e6f7',
    storageBucket: 'agrisense-pot511-1e6f7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyADErqkDZWQz8aXKIg_sKOptsR0vd-UfCQ',
    appId: '1:852916987468:ios:9ab8411d0775428b29b6e9',
    messagingSenderId: '852916987468',
    projectId: 'agrisense-pot511-1e6f7',
    storageBucket: 'agrisense-pot511-1e6f7.firebasestorage.app',
    iosBundleId: 'com.example.agrisense',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyADErqkDZWQz8aXKIg_sKOptsR0vd-UfCQ',
    appId: '1:852916987468:ios:9ab8411d0775428b29b6e9',
    messagingSenderId: '852916987468',
    projectId: 'agrisense-pot511-1e6f7',
    storageBucket: 'agrisense-pot511-1e6f7.firebasestorage.app',
    iosBundleId: 'com.example.agrisense',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAs_TPPh9kPwktZ6lngv7PxNoH572_iMf4',
    appId: '1:852916987468:web:eacbc947689e809f29b6e9',
    messagingSenderId: '852916987468',
    projectId: 'agrisense-pot511-1e6f7',
    authDomain: 'agrisense-pot511-1e6f7.firebaseapp.com',
    storageBucket: 'agrisense-pot511-1e6f7.firebasestorage.app',
    measurementId: 'G-04P37SEFKC',
  );
}
